services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    env_file:
      - ./api/.env
    volumes:
      - postgres-volume:/var/lib/postgresql/data

volumes:
  postgres-volume: