services:
    db:
        image: postgres
        container_name: postgres
        restart: always
        ports:
            - 5433:5432
        env_file:
            - .env
        volumes:
            - postgres-volume:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
            interval: 10s
            timeout: 5s
            retries: 5

    api:
        container_name: api
        build: .
        ports:
            - 4000:4000
        depends_on:
            db:
                condition: service_healthy
        env_file:
            - .env

volumes:
    postgres-volume:
