name: Homolog

on:
  push:
    branches:
      - develop
  workflow_dispatch:
    
jobs:
  build:
    runs-on: [self-hosted, homolog]
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create back-end env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_PORT: ${{secrets.PORT}}
          envkey_POSTGRES_USERNAME: ${{secrets.POSTGRES_USERNAME}}
          envkey_POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          envkey_POSTGRES_DATABASE: ${{secrets.POSTGRES_DATABASE}}
          envkey_POSTGRES_HOST: ${{secrets.POSTGRES_HOST}}
          envkey_POSTGRES_PORT: ${{secrets.POSTGRES_PORT}}
          envkey_JWT_SECRET: ${{secrets.JWT_SECRET}}
          envkey_DATABASE_URL: ${{secrets.DATABASE_URL}}
          directory: api
          file_name: .env
          fail_on_empty: true
      - name: Create front-end env file
        uses: SpicyPizza/create-envfile@v1.3.1
        with:
          envkey_VITE_API_BASE_URL: ${{secrets.VITE_API_BASE_URL}}
          directory: app
          file_name: .env
          fail_on_empty: true
      - name: Run docker compose down
        run: docker compose down -v

      - name: Run docker compose up
        run: docker compose up --build -d