name: Pull Request on Github
on: [pull_request]

jobs:
  PullRequest-GitHub:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Create .env.test file
        run: |
          echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/postgres" > api/.env.test

      - name: Install dependencies for API
        run: |
          cd api
          npm install

      - name: Run tests for API
        run: |
          cd api
          npm run test:pr:init

  Build-Test:
    runs-on: ubuntu-latest
    needs: PullRequest-GitHub  
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies for API
        run: |
          cd api
          npm install

      - name: Build API
        run: |
          cd api
          npm run build  # Certifique-se de que seu package.json tem um script "build"

      - name: Install dependencies for Frontend
        run: |
          cd app
          yarn install --frozen-lockfile

      - name: Build Frontend
        run: |
          cd app
          yarn build
